version: '3.5'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
    container_name: db_postgres

  redis:
    image: redis
    container_name: redis_container
    restart: unless-stopped

  frontend:
    image: front-exerc
    ports:
      - 5000:5000

  backend:
    image: back-exerc
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
    environment:
      - REDIS=redis_container
      - DB_PASSWORD=example
      - DB_USERNAME=example
      - DB_HOST=db_postgres
