version: '3.5'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
    container_name: db_postgres
    volumes:
      - /tmp/database:/var/lib/postgres/data

  redis:
    image: redis
    container_name: redis_container
    restart: unless-stopped
    container_name: redis_container
    volumes:
      - redisdata:/data

  frontend:
    image: 35front
    container_name: frontend

  backend:
    image: 35back
    depends_on:
      - redis
      - db
    environment:
      - REDIS=redis_container
      - DB_PASSWORD=example
      - DB_USERNAME=example
      - DB_HOST=db_postgres
    container_name: backend

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
    container_name: nginx_container
    depends_on:
      - backend

volumes:
  redisdata:
